baseURL = 'https://ix.labitat.dk/'
languageCode = 'en-us'
title = 'LabIX'

[[module.imports]]
path = "github.com/willfaught/paige"

[paige.analytics]
disable = true

[paige.comments]
disable = true

[paige.date]
format = ":date_long"
source = "published"

[paige.menu]
breakpoint = "sm"
style = "underline"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "test"
name = "test"
url = "/test/"
weight = 10
