baseURL = "https://ix.labitat.dk/"
languageCode = "en-us"
title = "LabIX"
copyright = "LabIX project. [website Git repository](https://github.com/labitat/ix.labitat.dk)"
enableRobotsTXT = true
timezone = "Europe/Copenhagen"
enableGitInfo = true

[[module.imports]]
path = "github.com/willfaught/paige"

[paige.analytics]
disable = true

[paige.comments]
disable = true

[paige.date]
format = ":date_long"
source = "modified"

[paige.menu]
breakpoint = "sm"
style = "tabs"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10 # Sort by weight, left side weighs less

[[languages.en.menu.main]]
identifier = "members"
name = "Members"
url = "/members/"
weight = 20

[[languages.en.menu.main]]
identifier = "documentation"
name = "Documentation"
url = "/documentation/"
weight = 30

[[languages.en.menu.main]]
identifier = "bornhack"
name = "BornHack"
url = "/BornHack/"
weight = 40

[languages.en.menu.main.params.paige]
divider_below = true

# Git dates
[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[outputs]
home = ["html", "json", "rss"]
members = ["html", "json", "rss"]
documentation = ["html", "json", "rss"]
bornhack = ["html", "json", "rss"]